### ISSUE TITLE
Build instructions in README

### ISSUE THREAD

**Issue by stolk** [tavor/opengl-radiosity#8]
The README.md gives the incorrect build instructions.

It is missing the flux, and the tiny_obj_loader files.

Correct one:
g++ -o radiosity radiosity.cpp struct.cpp vector.cpp flux.cpp tiny_obj_loader.cc -lGLU -lGL -lglut

**Comment by stolk** [comment]
Also missing: instruction on launch options.
./radiosity <geometryfile> <nr-of-iterations> <debug>

**Comment by tavor** [comment]
Updated the readme to include those instructions.
